# Generated by Django 3.2.5 on 2021-07-09 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogcategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
