# Generated by Django 3.2.5 on 2021-07-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='contenta',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='emaila',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='namea',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phonea',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='timeStamp',
            new_name='timeStampa',
        ),
    ]
